### ISSUE TITLE
一键部署到Azure出现错误Website with given name proxywebapp already exists

### ISSUE THREAD

**Issue by Everyjoy** [scalaone/azure-openai-proxy#13]
proxyappplan可以部署，proxywebapp部署错误

**Comment by maopucheng** [comment]
我也出现过，怀疑是手残按了2次。我删除，重新部署，前缀改长一点，好像没问题。

**Comment by EchoShoot** [comment]
换一个名字就行了，每个人需要取一个独特的名字

**Comment by blrchen** [comment]
感谢@maopucheng和@EchoShoot的帮助。Azure webapp的名称在Azure范围内必须是全局唯一的，因为这是Azure网站的DNS前缀，所以必须选择一个未被他人使用的名称。
