### ISSUE TITLE
没有打字机那种感觉，用的axios没有相应的处理？

### ISSUE THREAD

**Issue by land007** [scalaone/azure-openai-proxy#15]
官方的api会每个字都尽量回消息到前端，而不是一个段落回一次。是azure的问题还是程序转发的问题，我还没有打印日志，希望能弄清楚问题原因。

**Comment by land007** [comment]
字符处理有问题，不能这样累加，否则会出下面的乱码
提供帮��，但我

**Comment by blrchen** [comment]
Azure在OpenAI模型的基础上添加了内容过滤功能，详情请参考[这里](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/content-filter)。这意味着模型的输出首先会被缓存到一定的字数，然后经过内容过滤后才会返回。这使得Azure ChatGPT的输出以段落而非单个词汇的形式呈现。

你可以考虑申请关闭Azure的内容过滤功能，看看这是否能解决问题。

**Comment by xsser** [comment]
哎 写文档的能力需要加强 没一行看懂的

**Comment by blrchen** [comment]
> 哎 写文档的能力需要加强 没一行看懂的

感谢反馈。此项目的代码和文档主要由ChatGPT生成，机器生成导致可读性下降。我们的主要关注点是确保功能的正确性，现阶段有许多用户已经测试并在生产系统上稳定运行了。如果文档存在问题，欢迎提交PR或开启一个问题描述详情，我们将会手动修复。

**Comment by blrchen** [comment]
Streaming效果可以在 [演示网站](https://chatgpt-minimal.vercel.app/) 体验。在Azure OpenAI内容过滤启用的情况下，输出会缓存到一定字数，经过内容过滤后才返回，这个是Azure OpenAI的行为，无法控制。
