### ISSUE TITLE
请求时出现resource not found

### ISSUE THREAD

**Issue by ghost** [scalaone/azure-openai-proxy#17]
在其他支持openai的插件上使用时，出现resource not found。我在插件中只填写了azure的密钥和endpoint，但是出现了这个问题，是需要添加其他的配置请求吗？

**Comment by blrchen** [comment]
必须按`AZURE_RESOURCE_ID:AZURE_MODEL_DEPLOYMENT:AZURE_API_KEY`这个格式提供key

resource not found 意味着Azure的OpenAI账号和密钥正确，但是模型部署名称不对。
