### ISSUE TITLE
trouble using stream mode

### ISSUE THREAD

**Issue by Lanny2020** [scalaone/azure-openai-proxy#4]
I've trouble using stream mode. Could you please provide an example client that demonstrates how to use Stream mode effectively?

**Comment by haha1903** [comment]
You may refer to the contents of the following URL: [CURL](https://paw.pt/hK3aO2Wi).

**Comment by blrchen** [comment]
@Lanny2020, thank you for reaching out. I've added a docker-compose file to simplify testing the streaming feature. Please follow the steps in the [README](https://github.com/scalaone/azure-openai-proxy/blob/main/README.en-US.md#local-running-and-testing-using-webchat-for-streaming-test) and let me know if it helps.
